# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
    core: ren/core@0.0.1
    aws-s3: circleci/aws-s3@1.0.0

_defaults: &defaults
    docker:
        - image: circleci/golang:1.13.3

jobs:
    deploy:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                key: go-mod-v3-{{ checksum "go.sum" }}
            - run:
                name: install tools
                command: |
                    go vet ./...
            - save_cache:
                key: go-mod-v3-{{ checksum "go.sum" }}
                paths:
                    - "~/go"
            - run:
                name: Build binaries
                command: |
                    go build -o "darknode_linux_amd64_$CIRCLE_BRANCH" ./cmd
            - run:
                name: install AWS CLI
                command: |
                    sudo apt install python-pip python-dev
                    sudo pip install awscli
            - aws-s3/copy:
                from: darknode_linux_amd64*
                to: 's3://releases.republicprotocol.com/darknode-cli/'
                arguments: '--acl public-read'

workflows:
    version: 2.1
    build:
        jobs:
            - deploy
