# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
    core: ren/core@0.0.1
    aws-s3: circleci/aws-s3@1.0.0

_defaults: &defaults
    machine: true

jobs:
    deploy:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: install golang
                command: |
                    wget https://dl.google.com/go/go1.12.2.linux-amd64.tar.gz
                    sudo tar -xf go1.12.2.linux-amd64.tar.gz
                    sudo rm -rf /usr/local/go
                    sudo mv go /usr/local
                    go version
            - restore_cache:
                key: go-mod-v3-{{ checksum "go.sum" }}
            - run:
                name: install tools
                command: |
                    go vet ./...
            - save_cache:
                key: go-mod-v3-{{ checksum "go.sum" }}
                paths:
                    - "~/go"
            - run:
                name: Build binaries
                command: |
                    go build -o darknode_linux_amd64 ./cmd
            - run:
                name: install AWS CLI
                command: |
                    sudo apt install python-pip python-dev
                    sudo pip install awscli
            - aws-s3/copy:
                from: darknode_linux_amd64
                to: 's3://releases.republicprotocol.com/darknode-cli/darknode_linux_amd64_new'
                arguments: '--acl public-read'

workflows:
    version: 2.1
    build:
        jobs:
            - deploy:
                filters:
                    branches:
                        only:
                            - master
                            - config