# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
    core: ren/core@0.0.1
    aws-s3: circleci/aws-s3@1.0.0

_defaults: &defaults
    docker:
        - image: techknowlogick/xgo:latest

jobs:
    deploy:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                key: go-mod-v3-{{ checksum "go.sum" }}
            - run:
                name: install tools
                command: |
                    go get src.techknowlogick.com/xgo
                    go get github.com/tcnksm/ghr
                    go vet ./...
            - save_cache:
                key: go-mod-v3-{{ checksum "go.sum" }}
                paths:
                    - "~/go"
            - run:
                name: Build binaries
                command: |
                    cd cmd
                    xgo --targets=linux/amd64,darwin-10.10/amd64 .
                    mkdir -p artifacts
                    mv cmd-linux-amd64 artifacts/darknode_linux_amd64
                    mv cmd-darwin-10.10-amd64 artifacts/darknode_darwin_amd64
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete 2.3.1 ./artifacts/

workflows:
    version: 2.1
    deployment:
        jobs:
            - deploy
