# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
    core: ren/core@0.0.1

_defaults: &defaults
    docker:
        - image: techknowlogick/xgo:latest

jobs:
    deploy:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: install tools
                command: |
                    go vet ./...
            - run:
                name: Build binaries
                command: |
                    cd cmd
                    go build -o darknode .
                    mv darknode ../artifacts/darknode_linux_amd64
                    env GOOS=darwin CGO_ENABLED=1 CC=o64-clang GOARCH=amd64 go build -o darknode .
                    mv darknode ../artifacts/darknode_darwin_amd64
                    go get github.com/tcnksm/ghr
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete 2.3.0 ../artifacts/

workflows:
    version: 2.1
    deployment:
        jobs:
            - deploy:
                filters:
                    branches:
                        only:
                            - master
                            - config