name: install script
on: [push]
jobs:
    bash:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Test installation script
              shell: bash
              run: |
                  ./artifacts/install.sh
            - name: Check binary is properly installed
              shell: bash
              run: |
                  source ~/.bash_profile || command -v darknode
    zsh:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Test installation script
              shell: zsh {0}
              run: |
                  ./artifacts/install.sh
            - name: Check binary is properly installed
              shell: zsh {0}
              run: |
                  source ~/.zprofile || command -v darknode