name: install script
on: [push]
jobs:
    bash:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Test installation script
              run:  cat ./artifacts/install.sh | sh
            - name: Check binary is properly installed
              run: |
                  source ~/.bash_profile || command -v darknode
    zsh:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Install zsh
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install zsh
            - name: Test installation script
              shell: zsh {0}
              run: cat ./artifacts/install.sh | sh
            - name: Check binary is properly installed
              shell: zsh {0}
              run: |
                  if [ -f "$HOME/.zprofile" ] ; then
                      source ~/.zprofile || command -v darknode
                  else
                      source ~/.profile || command -v darknode
                  fi
    ksh:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Install ksh
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install ksh
            - name: Test installation script
              shell: ksh {0}
              run: cat ./artifacts/install.sh | sh
            - name: Check binary is properly installed
              shell: ksh {0}
              run: |
                  source ~/.profile || command -v darknode



