name: install script
on: [push]
jobs:
    bash:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Test installation script
              run: |
                  ./artifacts/install.sh
            - name: Check binary is properly installed
              run: |
                  source ~/.bash_profile || command -v darknode
    zsh:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Install zsh
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install zsh
                  ls -la $HOME
            - name: Test installation script
              shell: zsh {0}
              run: |
                 zsh ./artifacts/install.sh
            - name: Check binary is properly installed
              shell: zsh {0}
              run: |
                  if [ -f "$HOME/.zprofile" ] ; then
                      source ~/.zprofile || command -v darknode
                  elif [ -f "$HOME/.zshrc" ] ; then
                      source ~/.zshrc || command -v darknode
                  elif [ -f "$HOME/.profile" ] ; then
                      source ~/.profile || command -v darknode
                  fi
