name: install
on: [push]
jobs:
    aws:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Test installation script
              run: |
                  ./artifacts/install.sh
            - name: source bash_profile
              run: |
                  source ~/.bash_profile
                  echo $PATH
                  ls ~/.darknode
            - name: Check binary is properly installed
              run: |
                  command -v darknode
