name: test
on: [push]
jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Decrypt the credential file
              env:
                  GCP_PASSPHRASE: ${{ secrets.GCP_PASSPHRASE }}
              run : |
                  mkdir $HOME/secrets
                  gpg --quiet --batch --yes --decrypt --passphrase="$GCP_PASSPHRASE" \
                  --output $HOME/secrets/credentials.json ./.github/workflows/credentials.json.gpg
                  echo ::set-env name=gcp_credentials::$HOME/secrets/credentials.json
            - name: Install terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 0.12.24
            - name: Run the integration tests
              env:
                  ACCESS_TOKEN   : ${{ secrets.ACCESS_TOKEN }}
                  aws_access_key : ${{ secrets.AWS_ACCESS_KEY_ID}}
                  aws_secret_key : ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                  do_token       : ${{ secrets.DO_TOKEN}}
              run: |
                  mkdir -p $HOME/.darknode/darknodes
                  go test -v --race -timeout 30m