name: go
on: [push]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Build with xgo
              uses: crazy-max/ghaction-xgo@v1
              working-directory: ./cmd
              with:
                  xgo_version: latest
                  dest: build
                  targets: linux/arm64,linux/amd64,darwin/amd64
                  v: true
                  x: false
                  buildmode: default
                  ldflags: -s -w
#            - name: Create Release
#              id: create_release
#              uses: actions/create-release@v1
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#              with:
#                  tag_name: testing
#                  release_name: testing
#                  draft: false
#                  prerelease: false